# Maintainer: SudoMaker
# Apollo - Game streaming server with virtual display support

pkgname=hermes
pkgver=0.4.0
pkgrel=1
pkgdesc="Self-hosted game streaming server with virtual display support"
arch=('x86_64')
url='https://github.com/MrOz59/Hermes'
license=('GPL-3.0-only')
install=hermes.install

depends=(
  'avahi'
  'curl'
  'libayatana-appindicator'
  'libcap'
  'libdrm'
  'libevdev'
  'libnotify'
  'libpulse'
  'libva'
  'libx11'
  'libxcb'
  'libxfixes'
  'libxrandr'
  'libxtst'
  'miniupnpc'
  'numactl'
  'openssl'
  'opus'
  'udev'
)

makedepends=(
  'base-devel'
  'cmake'
  'git'
  'git-lfs'
  'nodejs'
  'npm'
)

optdepends=(
  'cuda: NVIDIA GPU encoding support'
  'evdi: Virtual display support for streaming to headless clients (AUR)'
  'gamescope: optional Gamescope Steam Session app'
  'kscreen: KDE Plasma Wayland virtual-display activation'
  'wl-clipboard: Hermes text clipboard synchronization on Wayland'
  'xclip: Hermes text clipboard synchronization on X11'
  'libva-mesa-driver: AMD GPU encoding support'
)

# Hermes installs under its own /usr/bin/hermes and /usr/share/hermes paths and
# ships hermes.service, so it can be installed side by side with the apollo (AUR)
# and sunshine packages — useful while the project is experimental. No provides
# or conflicts are declared for those packages; the binaries and unit names are
# all distinct.

source=()
sha256sums=()

prepare() {
    cd "${startdir}"
    # A source checkout already containing the submodules needs no mutation
    # of .git metadata (for example, when building in a restricted sandbox).
    if [[ ! -d third-party/moonlight-common-c/enet ]]; then
      git submodule update --init --recursive
    fi
    if command -v git-lfs >/dev/null 2>&1; then
      git lfs pull
    fi
}

build() {
    cd "${startdir}"
    export BRANCH=local
    export BUILD_VERSION="${pkgver}"

    # CUDA is required so the package ships NVIDIA NVENC hardware encoding. The
    # build fails if the CUDA toolkit is missing (CUDA_FAIL_ON_MISSING defaults
    # to ON) — install the `cuda` package (a makedepend) before building.
    cmake -S . -B build \
      -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DSUNSHINE_EXECUTABLE_PATH=/usr/bin/hermes \
      -DSUNSHINE_ASSETS_DIR=share/hermes
    cmake --build build
}

package() {
    cd "${startdir}"
    DESTDIR="${pkgdir}" cmake --install build

    rm "${pkgdir}/usr/bin/sunshine"
    mv "${pkgdir}/usr/bin/sunshine-"* "${pkgdir}/usr/bin/hermes"

    # The systemd unit generated by CMake is named sunshine.service; rename it
    # to hermes.service so it does not collide with an apollo/sunshine install.
    if [[ -f "${pkgdir}/usr/lib/systemd/user/sunshine.service" ]]; then
      mv "${pkgdir}/usr/lib/systemd/user/sunshine.service" \
         "${pkgdir}/usr/lib/systemd/user/hermes.service"
    fi
}
